version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports: 
      - 80:8080
    volumes:
      - ~/server-data/nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped    
