version: '3'
services:
  db: 
    image: postgres
    container_name: nextcloud_db
    hostname: 'nextcloud_postgres'
    volumes:
      -  ~/server-data/nextcloud/postgres-data:/var/lib/postgresql/data
    
    ports:
      - 5432:5432

    environment: 
      #Make sure to change defaults
      - POSTGRES_DB=nextcloud_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  
    restart: unless-stopped    

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 8082:80 
    
    volumes: 
      - ~/server-data/nextcloud/data:/var/www/html

    depends_on:
      - db

    environment:
      #Make sure to change defaults
      - POSTGRES_HOST=nextcloud_postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

    restart: unless-stopped
