version: '3'
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - ~/server-data/radarr/config:/config
      - ~/server-data/jellyfin/media/Movies:/movies
      - ~/Downloads:/downloads

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
  
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - ~/server-data/sonarr/config:/config
      - ~/server-data/jellyfin/media/Shows:/tv
      - ~/Downloads:/downloads
  
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago
 
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    ports:
      - 9117:9117
    volumes:
      - ~/server-data/jackett/config:/config
  
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santiago

    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    volumes:
      - ~/server-data/qbittorrent/config:/config
      - ~/server-data/qbittorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080

    restart: unless-stopped
